### ISSUE TITLE
SASS code of decodeBBoxesOpt

### ISSUE THREAD

**Issue by mahmoodn** [mlcommons/inference_results_v2.0#14]
I would like to see the SASS code of a kernel called [decodeBBoxesOpt_kernel](https://github.com/mlcommons/inference_results_v2.0/blob/master/closed/NVIDIA/code/plugin/NMSOptPlugin/src/decodeBBoxesOpt.cu#L214) via nvdisasm, but it doesn't work.
According to the command below, the kernel name appears in the following files:
```
$ grep -r decodeBBoxesOpt_kernel build/
Binary file build/plugins/NMSOptPlugin/libnmsoptplugin.so matches
Binary file build/plugins/NMSOptPlugin/CMakeFiles/nmsoptplugin.dir/src/decodeBBoxesOpt.cu.o matches
```

However, I get the following error with nvdisasm
```
$ nvdisasm build/plugins/NMSOptPlugin/libnmsoptplugin.so
nvdisasm fatal   : build/plugins/NMSOptPlugin/libnmsoptplugin.so is not a supported Elf file
```
Any thoughts on that?

**Comment by nv-ananjappa** [comment]
@mahmoodn We can only provide support for reproducing the benchmarking results.

**Comment by nv-ananjappa** [comment]
@rnaidu02 Can we close this issue? Thanks.
