### ISSUE TITLE
Graph visualizer in RNNT

### ISSUE THREAD

**Issue by mahmoodn** [mlcommons/inference_results_v2.0#15]
Hi
Is it possible to disable the graph visualizer in RNNT in Nvidia implementation?

**Comment by nv-ananjappa** [comment]
@nvzhihanj Is this possible?

**Comment by nvzhihanj** [comment]
@mahmoodn I am not sure if I understand your request. Which graph visualizer are you talking about?

**Comment by mahmoodn** [comment]
Let me state the problem in this way. I want to use NVBit for RNNT but as described [here](https://github.com/NVlabs/NVBit/issues/104), it faces an error which is due to the cudaStreamBeginCapture() used in the RNNT code in [makeDecoderGraph()](https://github.com/mlcommons/inference_results_v2.0/blob/master/closed/NVIDIA/code/harness/harness_rnnt/main_rnnt.cc#L1728).

I don't know about the internals of that function, but I guess that is related to creating a graph. So, I want to know if there is a way to bypass that by disabling graph related things.

**Comment by nvzhihanj** [comment]
You can turn off the graph by specifying "--use_graph=False" in the config or command line.
