### ISSUE TITLE
Missing gpu_batch_size in NVIDIA custom system script

### ISSUE THREAD

**Issue by mahmoodn** [mlcommons/inference_results_v2.0#6]
Hi
It seems that the NVIDIA script [add_custom_system.py](https://github.com/mlcommons/inference_results_v2.0/blob/master/closed/NVIDIA/scripts/custom_systems/add_custom_system.py) doesn't add `gpu_batch_size` in the generated config files. That is needed by benchmarks and therefore, has to be added manually.

**Comment by nv-alicheng** [comment]
Hi mahmoodn,

I believe this bug was fixed internally, as I cannot reproduce it. The fix will be released with the v2.1 submission.
